### ISSUE TITLE
feature request: describe alternative bridging method

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/docs#17]
Add bridge depositEtherToL2, see Dani's tweet: https://x.com/dani_who_daniel/status/1747477406880067974?s=20

**Comment by Krshivam25** [comment]
Seems like this twitter URL doesn't exist

**Comment by VictoryWekwa** [comment]
Hello, is this issue still open? i would want to e assigned to this. Thank you

**Comment by coinsspor** [comment]
this tweet is deleted
