### ISSUE TITLE
bug report: L2 node doesn't sync

### ISSUE THREAD

**Issue by ymittal** [taikoxyz/docs#18]
I set up a Holesky node on my VPS. Node is fully synced (both consensus and execution).

I then set up an L2 node with my Holesky node as the L1 on the same machine. When I try to run it, everything looks good for 2-3 mins, node starts to sync but then it abruptly stops and no blocks get processed. See Grafana for L2 below
<img width="1467" alt="image" src="https://github.com/taikoxyz/docs/assets/8350076/32d05697-c32d-4103-aaf2-d751e6644d41">

I have tried taking down both nodes and restarting multiple times, but to no avail. Multiple people including myself see this under `docker compose logs -f` on the L2 node. `lastVerifiedBlock=10283` (the exact same for a few folks). I have had my L2 node running for 12h+ at this point, but no blocks have been processed after the first few mins.
![image](https://github.com/taikoxyz/docs/assets/8350076/f4402b54-e12e-4a6b-bf8d-e47b19f79c65)

Totally blocked and the only related FAQ in Discord is [this](https://discord.com/channels/984015101017346058/1193979506080354304) wherein we're asked to ignore the error. I don't see any other error logs in the trace.

**Comment by BigWise7** [comment]
Same issue here and with 5 other people, all can't get past the lastVerifiedBlockId = 10283 on my proposer running on a VPS.

I actually had 2 provers running on dedicated servers which were syncing fine up to the latest block (~17K) and I decided to change one of them to a proposer to see if it was just an issue with proposers. There was no trouble, it synced correctly.

With this limited isolation test, and hearing from others in Discord, running on a VPS seems to be the common denominator.

**Comment by rico0610** [comment]
Same issue here.
<img width="1191" alt="Screenshot 2024-01-18 at 11 54 50 AM" src="https://github.com/taikoxyz/docs/assets/81943661/56839fdd-b1d3-4f8f-8579-1ad45e16a5e0">

**Comment by SamyKn** [comment]
mine synched till 19K , works for a random amount of time then stops.
i restart the node , starts working then stops again.
