### ISSUE TITLE
bug report: Node stopping

### ISSUE THREAD

**Issue by sharkmoca** [taikoxyz/docs#22]
![Screenshot 2024-01-17 173424](https://github.com/taikoxyz/docs/assets/156977562/9a985a77-60cc-4fe6-b21f-81995e5abae8)
![Screenshot 2024-01-17 173758](https://github.com/taikoxyz/docs/assets/156977562/c4a3f2c1-76ca-45b1-8da6-5da0ec82798f)
![Screenshot 2024-01-17 173550](https://github.com/taikoxyz/docs/assets/156977562/e5f46205-132c-47e7-80fa-8a72c586e14f)

I don't understand what's happening. The node apparently works for a while and stops. I've reinstalled it several times and the error remains.

**Comment by davidtaikocha** [comment]
What's your CPU / Memory graph in grafana?
