### ISSUE TITLE
feature request: show some missing client diffs

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/docs#32]
eth_syncing did not behave as expected. please document. see: https://github.com/taikoxyz/taiko-client/issues/537

**Comment by davidtaikocha** [comment]
Maybe we can update this behavior to make it as expected, let me check next week.

**Comment by d1onys1us** [comment]
> Maybe we can update this `eth_syncing` behavior to make it as expected, let me check next week.

oh that could be cool.

actually i don't love `eth_syncing` on geth either. because if it doesn't really tell you if it is fully synced. it will just return `false` if it hasn't started, and also `false` if it is fully synced. so i need to fetch the block height and compare against a fully synced Taiko node RPC for my to check on the user machine if they are fully synced... do you know a better way?
