### ISSUE TITLE
Update swagger UI links for Relayer and Event Indexer API to A6 testnet

### ISSUE THREAD

**Issue by muskbuster** [taikoxyz/docs#37]
The current swagger API references are pointed to the older testnet and needs to be updated

https://relayer-swagger.taiko.xyz/#/default/get-block-info - Relayer 
https://eventindexer-swagger.taiko.xyz/#/ - event indexer

Reference page in docs - https://docs.taiko.xyz/api-reference/bridge-relayer-api/

![image](https://github.com/taikoxyz/docs/assets/81789395/7bfd4112-121c-4458-b985-db276692ad9d)

**Comment by davidtaikocha** [comment]
Closed by https://github.com/taikoxyz/taiko-mono/pull/15755
