### ISSUE TITLE
docker compose up description error

### ISSUE THREAD

**Issue by 0x9bb1** [taikoxyz/docs#94]
### Describe the bug

When I run the command `docker compose up --profile l2_execution_engine -d` as per the documentation, it prompts `unknown flag: --profile`. I changed the command to `docker compose --profile l2_execution_engine up -d`, and it worked. This seems to be a description error.

### Steps to reproduce

`docker compose up --profile l2_execution_engine -d`

### Spam policy

- [X] I verify that this issue is NOT SPAM and understand SPAM issues will be closed and reported to GitHub, resulting in ACCOUNT TERMINATION.

**Comment by knikolaeff** [comment]
There are actually 2 such typos. Fixed in this PR. Please, review. 

https://github.com/taikoxyz/docs/pull/103
